name: logsnag
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
repository: https://github.com/Joran-Dob/logsnag/

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  mocktail: ^0.3.0
dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  http: ^0.13.5
