name: logsnag
description: A Dart and Flutter package for sending logs and insights to LogSnag.
version: 0.2.0+2
repository: https://github.com/Joran-Dob/logsnag/

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  http: ^1.1.0
